#!/usr/bin/env node
// Regenerates the error catalog from the Move sources.
//
//   node tooling/error-codes/generate.mjs [--check]
//
// --check exits non-zero if the committed output is stale, for CI.

import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { buildCatalog } from './parse-move-errors.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(HERE, '..', '..')
const OUT_DIR = join(HERE, 'generated')
const SOURCE_ROOTS = ['packages/triex/sources', 'packages/token/sources']

const catalog = buildCatalog(SOURCE_ROOTS.map(r => join(REPO_ROOT, r)), REPO_ROOT)

// --- lints -------------------------------------------------------------------
// These are the failure modes a hand-maintained code table drifts into. Catching
// them here is the whole reason the table is generated rather than written by hand.
const problems = []

for (const c of catalog.collisions) {
  problems.push(`duplicate code ${c.code} in module '${c.module}': ${c.names.join(' and ')}`)
}
for (const e of catalog.unkeyed) {
  problems.push(`${e.file}:${e.line} ${e.module}::${e.name} has no stable code — add #[error(code = N)]`)
}
for (const e of catalog.entries) {
  // A clever error with code 0 is indistinguishable from an un-annotated #[error].
  if (e.clever && e.code === 0) problems.push(`${e.file}:${e.line} ${e.module}::${e.name} uses #[error(code = 0)]; 0 is reserved as "unset"`)
}

// Gaps are not errors, but they are how a hand-kept table rots, so report them.
const gaps = []
for (const [module, table] of Object.entries(catalog.byModule)) {
  const codes = Object.keys(table).map(Number).sort((a, b) => a - b)
  const missing = []
  for (let i = codes[0]; i < codes[codes.length - 1]; i++) if (!codes.includes(i)) missing.push(i)
  if (missing.length > 0) gaps.push({ module, missing })
}

// --- emit --------------------------------------------------------------------
const payload = {
  $comment: 'Generated by tooling/error-codes/generate.mjs. Do not edit by hand.',
  sourceRoots: SOURCE_ROOTS,
  byModule: Object.fromEntries(
    Object.entries(catalog.byModule).map(([module, table]) => [
      module,
      Object.fromEntries(
        Object.entries(table).map(([code, e]) => [
          code,
          { name: e.name, label: e.label, message: e.message, clever: e.clever, file: e.file, line: e.line },
        ]),
      ),
    ]),
  ),
}

const json = JSON.stringify(payload, null, 2) + '\n'

const names = catalog.entries.map(e => `  | '${e.module}::${e.name}'`).join('\n')
const ts = `// Generated by tooling/error-codes/generate.mjs. Do not edit by hand.
// Regenerate with: node tooling/error-codes/generate.mjs

export type TriexErrorName =
${names}

export interface TriexErrorEntry {
  name: string
  label: string
  message: string | null
  clever: boolean
  file: string
  line: number
}

export const ERROR_CODES: Record<string, Record<number, TriexErrorEntry>> = ${JSON.stringify(payload.byModule, null, 2)}

export default ERROR_CODES
`

const targets = [
  [join(OUT_DIR, 'error-codes.json'), json],
  [join(OUT_DIR, 'error-codes.ts'), ts],
]

const check = process.argv.includes('--check')
let stale = false
for (const [path, content] of targets) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      stale = true
      console.error(`stale: ${path}`)
    }
  } else {
    writeFileSync(path, content)
  }
}

console.error(`${catalog.entries.length} error constants across ${Object.keys(catalog.byModule).length} modules`)
if (gaps.length > 0) {
  console.error('\ngaps in numbering (harmless, but a sign of deleted constants):')
  for (const g of gaps) console.error(`  ${g.module}: missing ${g.missing.join(', ')}`)
}
if (problems.length > 0) {
  console.error('\nproblems:')
  for (const p of problems) console.error(`  ${p}`)
  process.exit(1)
}
if (check && stale) {
  console.error('\nerror-codes output is stale; run: node tooling/error-codes/generate.mjs')
  process.exit(1)
}
if (!check) console.error(`wrote ${targets.map(([p]) => p.replace(REPO_ROOT + '/', '')).join(' and ')}`)
